package ${basePackageName}.${table.module}.${table.modelName?lower_case}.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class Base${table.modelName}<M extends Base${table.modelName}<M>> extends Model<M> implements IBean {
	<#list listColumn as column>
	public M set${column.fieldName?cap_first}(${column.javaType} ${column.fieldName}) {
		set("${column.fieldName}", ${column.fieldName});
		return (M)this;
	}
	public ${column.javaType} get${column.fieldName?cap_first}() {
		return get("${column.fieldName}");
	}
	</#list>
}
