package com.xxx.market.model;

import com.xxx.market.model.base.BaseAgent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agent extends BaseAgent<Agent> {
	public static final Agent dao = new Agent();
	public static final String table = "t_agent";
}
