package com.xxx.market.model;

import com.xxx.market.model.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area();
	public static final String table = "t_area";
}
