package com.xxx.market.model;

import com.xxx.market.model.base.BaseBuyerRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyerRecharge extends BaseBuyerRecharge<BuyerRecharge> {
	public static final BuyerRecharge dao = new BuyerRecharge();
	public static final String table = "t_buyer_recharge";
}
