package com.xxx.market.model;

import com.xxx.market.model.base.BaseCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cart extends BaseCart<Cart> {
	public static final Cart dao = new Cart();
	public static final String table = "t_cart";
}
