package com.xxx.market.model;

import com.xxx.market.model.base.BaseCashbackSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CashbackSet extends BaseCashbackSet<CashbackSet> {
	public static final CashbackSet dao = new CashbackSet();
	public static final String table = "t_cashback_set";
}
