package com.xxx.market.model;

import com.xxx.market.model.base.BaseCommissionRate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommissionRate extends BaseCommissionRate<CommissionRate> {
	public static final CommissionRate dao = new CommissionRate();
	public static final String table = "t_commission_rate";
}
