package com.xxx.market.model;

import com.xxx.market.model.base.BaseExpressImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExpressImg extends BaseExpressImg<ExpressImg> {
	public static final ExpressImg dao = new ExpressImg();
	public static final String table = "t_express_img";
}
