package com.xxx.market.model;

import com.xxx.market.model.base.BaseExpressTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExpressTemplate extends BaseExpressTemplate<ExpressTemplate> {
	public static final ExpressTemplate dao = new ExpressTemplate();
	public static final String table = "t_express_template";
}
