package com.xxx.market.model;

import com.xxx.market.model.base.BaseExpressComp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExpressComp extends BaseExpressComp<ExpressComp> {
	public static final ExpressComp dao = new ExpressComp();
	public static final String table = "t_express_comp";
}
