package com.xxx.market.model;

import com.xxx.market.model.base.BaseFullCut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FullCut extends BaseFullCut<FullCut> {
	public static final FullCut dao = new FullCut();
	public static final String table = "t_full_cut";
}
