package com.xxx.market.model;

import com.xxx.market.model.base.BaseImageGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImageGroup extends BaseImageGroup<ImageGroup> {
	public static final ImageGroup dao = new ImageGroup();
	public static final String table = "t_image_group";
}
