package com.xxx.market.model;

import com.xxx.market.model.base.BaseInvoiceTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvoiceTemplate extends BaseInvoiceTemplate<InvoiceTemplate> {
	public static final InvoiceTemplate dao = new InvoiceTemplate();
	public static final String table = "t_invoice_template";
}
