package com.xxx.market.model;

import com.xxx.market.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order dao = new Order();
	public static final String table = "t_order";
}
