package com.xxx.market.model;

import com.xxx.market.model.base.BaseOrderItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderItem extends BaseOrderItem<OrderItem> {
	public static final OrderItem dao = new OrderItem();
	public static final String table = "t_order_item";
}
