package com.xxx.market.model;

import com.xxx.market.model.base.BaseOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderLog extends BaseOrderLog<OrderLog> {
	public static final OrderLog dao = new OrderLog();
	public static final String table = "t_order_log";
}
