package com.xxx.market.model;

import com.xxx.market.model.base.BaseProductReview;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductReview extends BaseProductReview<ProductReview> {
	public static final ProductReview dao = new ProductReview();
	public static final String table = "t_product_review";
}
