package com.xxx.market.model;

import com.xxx.market.model.base.BasePromotionSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionSet extends BasePromotionSet<PromotionSet> {
	public static final PromotionSet dao = new PromotionSet();
	public static final String table = "t_promotion_set";
}
