package com.xxx.market.model;

import com.xxx.market.model.base.BasePurchaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseOrder extends BasePurchaseOrder<PurchaseOrder> {
	public static final PurchaseOrder dao = new PurchaseOrder();
	public static final String table = "t_purchase_order";
}
