package com.xxx.market.model;

import com.xxx.market.model.base.BaseQiandao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Qiandao extends BaseQiandao<Qiandao> {
	public static final Qiandao dao = new Qiandao();
	public static final String table = "t_qiandao";
}
