package com.xxx.market.model;

import com.xxx.market.model.base.BaseQiandaoConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QiandaoConfig extends BaseQiandaoConfig<QiandaoConfig> {
	public static final QiandaoConfig dao = new QiandaoConfig();
	public static final String table = "t_qiandao_config";
}
