package com.xxx.market.model;

import com.xxx.market.model.base.BaseRefund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Refund extends BaseRefund<Refund> {
	public static final Refund dao = new Refund();
	public static final String table = "t_refund";
}
