package com.xxx.market.model;

import com.xxx.market.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	public static final String table = "t_role";
}
