package com.xxx.market.model;

import com.xxx.market.model.base.BaseShipping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shipping extends BaseShipping<Shipping> {
	public static final Shipping dao = new Shipping();
	public static final String table = "t_shipping";
}
