package com.xxx.market.model;

import com.xxx.market.model.base.BaseShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shop extends BaseShop<Shop> {
	public static final Shop dao = new Shop();
	public static final String table = "t_shop";
}
